<?php


$title = 'Edit Task';
$this->headTitle($title);
?>
<h1><?= $this->escapeHtml($title) ?></h1>
<?php
$task = $form->get('title');
$task->setAttribute('class', 'form-control');
$task->setAttribute('placeholder', ' title');

$descriptionn = $form->get('descriptionn');
$descriptionn->setAttribute('class', 'form-control');
$descriptionn->setAttribute('placeholder', 'descriptionn');

$creation_date = $form->get('creation_date');
$creation_date->setAttribute('class', 'form-control');
$creation_date->setAttribute('placeholder', 'creation_date');

$statuss = $form->get('statuss');
$statuss->setAttribute('class', 'form-control');
$statuss->setAttribute('placeholder', 'statuss');



$submit = $form->get('submit');
$submit->setAttribute('class', 'btn btn-primary');

$form->setAttribute('action', $this->url('task', [
    'action' => 'edit',
    'id'     => $id,
]));
$form->prepare();

echo $this->form()->openTag($form);
?>
<div class="form-group">
    <?= $this->formLabel($task) ?>
    <?= $this->formElement($task) ?>
    <?= $this->formElementErrors()->render($task, ['class' => 'help-block']) ?>
</div>

<div class="form-group">
    <?= $this->formLabel($descriptionn) ?>
    <?= $this->formElement($descriptionn) ?>
    <?= $this->formElementErrors()->render($descriptionn, ['class' => 'help-block']) ?>
</div>

<div class="form-group">
    <?= $this->formLabel($statuss) ?>
    <?= $this->formElement($statuss) ?>
    <?= $this->formElementErrors()->render($statuss, ['class' => 'help-block']) ?>
</div>

<?php
echo $this->formSubmit($submit);
echo $this->formHidden($form->get('id'));
echo $this->form()->closeTag();